//! Invite flow for securely sharing projects between peers.
//!
//! Uses SPAKE2 (a Password-Authenticated Key Exchange) to establish
//! a shared session key from the invite passphrase. This prevents
//! offline dictionary attacks by a relay or network observer — even
//! one who records all exchanged messages cannot brute-force the
//! passphrase offline.
//!
//! Security properties:
//! - Transport is E2E encrypted via iroh QUIC (defense in depth)
//! - SPAKE2 proves both sides know the invite code (PAKE property)
//! - Session key is independent of passphrase (prevents offline attack)
//! - Random nonces in XChaCha20-Poly1305 prevent replay
//! - TTL + attempt limits prevent online brute force
//! - One-time use: invite code is consumed after first acceptance

use std::time::{Duration, Instant};

use chacha20poly1305::aead::{Aead, KeyInit};
use chacha20poly1305::XChaCha20Poly1305;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zeroize::Zeroize;

/// ALPN for the invite protocol (separate from sync).
pub const INVITE_ALPN: &[u8] = b"/p2p-notes/invite/1";

/// Default TTL for invite codes.
pub const DEFAULT_INVITE_TTL: Duration = Duration::from_secs(10 * 60); // 10 minutes
const INVITE_HANDSHAKE_TIMEOUT: Duration = Duration::from_secs(30);

pub fn current_invite_ttl() -> Duration {
    if std::env::var("P2P_E2E").ok().as_deref() != Some("1") {
        return DEFAULT_INVITE_TTL;
    }

    std::env::var("P2P_INVITE_TTL_SECS")
        .ok()
        .and_then(|raw| raw.parse::<u64>().ok())
        .filter(|secs| *secs > 0)
        .map(Duration::from_secs)
        .unwrap_or(DEFAULT_INVITE_TTL)
}

/// Maximum handshake attempts per invite code.
pub const MAX_HANDSHAKE_ATTEMPTS: u32 = 3;

/// An invite code generated by the project owner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InviteCode {
    /// The secret passphrase (e.g., "tiger-marble-ocean-violet-canyon-frost").
    pub passphrase: String,
    /// The owner's peer ID, so the invitee knows who to connect to.
    pub peer_id: String,
    /// When this invite expires (ISO 8601).
    pub expires_at: chrono::DateTime<chrono::Utc>,
}

/// Data sent from Owner to Invitee after successful handshake.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvitePayload {
    /// Invite/session identifiers for durable resume.
    #[serde(default)]
    pub invite_id: String,
    #[serde(default)]
    pub session_id: String,
    /// Project ID.
    pub project_id: String,
    /// Project name.
    pub project_name: String,
    /// Role assigned to the invitee ("editor" or "viewer").
    pub role: String,
    /// The full manifest binary (Automerge document), hex-encoded.
    pub manifest_hex: String,
    /// Owner's X25519 public key (hex-encoded, 32 bytes). Stored by invitee for future key rotation wrapping.
    #[serde(default)]
    pub owner_x25519_public_hex: String,
    /// Current epoch key (hex-encoded, 32 bytes). Transmitted inside the SPAKE2-encrypted payload.
    /// This is safe because the payload is encrypted with the session key derived from the SPAKE2 handshake.
    /// For subsequent key rotations after peer removal, X25519 ECDH wrapping (wrap_epoch_key/unwrap_epoch_key)
    /// is used to distribute new epoch keys without the SPAKE2 channel.
    #[serde(default)]
    pub epoch_key_hex: String,
    /// Current epoch number.
    #[serde(default)]
    pub epoch: u32,
}

/// Tracks an active invite on the Owner side.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InviteSessionPhase {
    Reserved,
    PayloadPrepared,
    PayloadSent,
    AwaitingPreparedAck,
    PreparedAckReceived,
    Committed,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InviteReservation {
    pub session_id: String,
    pub invitee_peer_id: String,
    pub reserved_at: Instant,
    pub timeout_at: Instant,
    pub phase: InviteSessionPhase,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InviteConsumed {
    pub session_id: String,
    pub invitee_peer_id: String,
    pub consumed_at: Instant,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InviteCommittedPendingAck {
    pub session_id: String,
    pub invitee_peer_id: String,
    pub committed_at: Instant,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InviteState {
    Open,
    Reserved(InviteReservation),
    CommittedPendingAck(InviteCommittedPendingAck),
    Consumed(InviteConsumed),
}

#[derive(Debug, Clone)]
pub struct PendingInvite {
    pub invite_id: String,
    pub code: InviteCode,
    pub created_at: Instant,
    pub attempts: u32,
    pub project_name: String,
    pub project_id: String,
    /// Role to assign the invitee.
    pub invite_role: String,
    pub state: InviteState,
    #[cfg(test)]
    pub manifest_data: Vec<u8>,
    #[cfg(test)]
    pub owner_x25519_public: Option<[u8; 32]>,
    #[cfg(test)]
    pub epoch_key: Option<[u8; 32]>,
    #[cfg(test)]
    pub current_epoch: u32,
}

impl PendingInvite {
    pub fn is_expired(&self) -> bool {
        chrono::Utc::now() > self.code.expires_at
    }

    pub fn is_exhausted(&self) -> bool {
        self.attempts >= MAX_HANDSHAKE_ATTEMPTS
    }

    pub fn is_available(&self) -> bool {
        matches!(self.state, InviteState::Open)
    }
}

/// Generate a random passphrase of `n` words.
/// Each word gives 8 bits of entropy (256-word list), so 6 words = 48 bits.
pub fn generate_passphrase(word_count: usize) -> String {
    // Exactly 256 words for uniform 8-bit selection with no modulo bias.
    const WORDS: &[&str] = &[
        "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball", "band",
        "bank", "base", "bath", "bean", "bear", "beat", "been", "bell", "belt", "best", "bill",
        "bird", "bite", "blow", "blue", "boat", "body", "bomb", "bond", "bone", "book", "boot",
        "born", "boss", "both", "bowl", "bulk", "burn", "bush", "busy", "calm", "came", "camp",
        "card", "care", "case", "cash", "cast", "cave", "cell", "chat", "chip", "city", "clam",
        "clay", "clip", "club", "clue", "coal", "coat", "code", "coin", "cold", "cole", "come",
        "cook", "cool", "cope", "copy", "core", "cost", "crew", "crop", "crow", "cure", "curl",
        "cute", "dale", "dame", "damp", "dare", "dark", "data", "date", "dawn", "deal", "dear",
        "debt", "deep", "deer", "demo", "deny", "desk", "dial", "diet", "dirt", "dish", "disk",
        "dock", "does", "dome", "done", "door", "dose", "dove", "down", "draw", "drew", "drop",
        "drum", "dual", "duke", "dull", "dump", "dune", "dust", "duty", "each", "earn", "ease",
        "east", "easy", "edge", "else", "epic", "euro", "even", "ever", "evil", "exam", "exit",
        "face", "fact", "fail", "fair", "fall", "fame", "fang", "farm", "fast", "fate", "fear",
        "feed", "feel", "feet", "fell", "felt", "file", "fill", "film", "find", "fine", "fire",
        "firm", "fish", "fist", "five", "flag", "flat", "fled", "flew", "flip", "flow", "foam",
        "fold", "folk", "fond", "font", "food", "foot", "ford", "fore", "fork", "form", "fort",
        "foul", "four", "free", "from", "fuel", "full", "fund", "fury", "fuse", "gain", "gale",
        "game", "gang", "gate", "gave", "gaze", "gear", "gene", "gift", "girl", "give", "glad",
        "glow", "glue", "goat", "goes", "gold", "golf", "gone", "good", "grab", "gray", "grew",
        "grid", "grim", "grip", "grow", "gulf", "guru", "gust", "hack", "hail", "hair", "half",
        "hall", "halt", "hand", "hang", "hard", "harm", "hate", "have", "hawk", "haze", "head",
        "heal", "heap", "hear", "heat", "held", "help", "herb", "here", "hero", "hide", "high",
        "hike", "hill", "hint", "hire", "hold", "hole", "holy", "home", "hood", "hook", "hope",
        "horn", "host", "hour",
    ];
    const _: () = assert!(
        WORDS.len() == 256,
        "word list must have exactly 256 entries for unbiased selection"
    );

    let mut words = Vec::with_capacity(word_count);
    let mut rand_bytes = vec![0u8; word_count];
    getrandom::fill(&mut rand_bytes).expect("failed to generate random bytes");

    for byte in rand_bytes {
        let idx = byte as usize % WORDS.len();
        words.push(WORDS[idx]);
    }

    words.join("-")
}

// ── SPAKE2 Handshake ──────────────────────────────────────────────────

/// Start the owner side of the SPAKE2 handshake.
/// Returns the SPAKE2 state and the outgoing message to send to the invitee.
pub fn start_owner_handshake(
    passphrase: &str,
) -> (spake2::Spake2<spake2::Ed25519Group>, Vec<u8>) {
    let (state, msg) = spake2::Spake2::<spake2::Ed25519Group>::start_a(
        &spake2::Password::new(passphrase.as_bytes()),
        &spake2::Identity::new(b"p2p-notes-owner"),
        &spake2::Identity::new(b"p2p-notes-invitee"),
    );
    (state, msg)
}

/// Start the invitee side of the SPAKE2 handshake.
/// Returns the SPAKE2 state and the outgoing message to send to the owner.
pub fn start_invitee_handshake(
    passphrase: &str,
) -> (spake2::Spake2<spake2::Ed25519Group>, Vec<u8>) {
    let (state, msg) = spake2::Spake2::<spake2::Ed25519Group>::start_b(
        &spake2::Password::new(passphrase.as_bytes()),
        &spake2::Identity::new(b"p2p-notes-owner"),
        &spake2::Identity::new(b"p2p-notes-invitee"),
    );
    (state, msg)
}

/// Finish the SPAKE2 handshake by processing the peer's message.
/// Returns the shared session key (32 bytes).
pub fn finish_handshake(
    state: spake2::Spake2<spake2::Ed25519Group>,
    incoming_msg: &[u8],
) -> Result<Vec<u8>, InviteError> {
    state
        .finish(incoming_msg)
        .map_err(|_| InviteError::VerificationFailed)
}

/// Compute a Short Authentication String (SAS) for visual verification.
/// Returns a 4-digit numeric code derived from the shared key.
pub fn compute_sas(shared_key: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let hash = Sha256::digest(shared_key);
    let code = u32::from_be_bytes([hash[0], hash[1], hash[2], hash[3]]) % 10000;
    format!("{code:04}")
}

// ── Payload Encryption ─────────────────────────────────────────────────

/// Encrypt a payload using XChaCha20-Poly1305 with the SPAKE2 session key.
pub fn encrypt_payload(key: &[u8], plaintext: &[u8]) -> Result<Vec<u8>, InviteError> {
    if key.len() < 32 {
        return Err(InviteError::CryptoError);
    }
    let cipher_key = chacha20poly1305::Key::from_slice(&key[..32]);
    let cipher = XChaCha20Poly1305::new(cipher_key);

    let mut nonce_bytes = [0u8; 24];
    getrandom::fill(&mut nonce_bytes).map_err(|_| InviteError::CryptoError)?;
    let nonce = chacha20poly1305::XNonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, plaintext)
        .map_err(|_| InviteError::CryptoError)?;

    let mut result = Vec::with_capacity(24 + ciphertext.len());
    result.extend_from_slice(&nonce_bytes);
    result.extend_from_slice(&ciphertext);
    Ok(result)
}

/// Decrypt a payload using XChaCha20-Poly1305 with the SPAKE2 session key.
pub fn decrypt_payload(key: &[u8], data: &[u8]) -> Result<Vec<u8>, InviteError> {
    if data.len() < 24 || key.len() < 32 {
        return Err(InviteError::InvalidPayload);
    }

    let cipher_key = chacha20poly1305::Key::from_slice(&key[..32]);
    let cipher = XChaCha20Poly1305::new(cipher_key);

    let nonce = chacha20poly1305::XNonce::from_slice(&data[..24]);
    let ciphertext = &data[24..];

    cipher
        .decrypt(nonce, ciphertext)
        .map_err(|_| InviteError::DecryptionFailed)
}

// ── Owner-side Invite Handler ─────────────────────────────────────────

use std::sync::Arc;
use std::{future::Future, pin::Pin};

use dashmap::DashMap;
use iroh::endpoint::Connection;
use iroh::protocol::AcceptError;
use tokio::io::AsyncWriteExt;

/// Event emitted when an invite is successfully accepted.
#[derive(Debug, Clone)]
pub struct InviteAccepted {
    /// The project name that was shared.
    pub project_name: String,
    /// The invitee's peer ID (from the iroh connection).
    pub invitee_peer_id: String,
    /// The role assigned to the invitee.
    pub role: String,
}

#[derive(Debug, Clone)]
pub struct InviteAcceptanceContext {
    pub invite_id: String,
    pub session_id: String,
    pub passphrase: String,
    pub project_name: String,
    pub project_id: String,
    pub role: String,
    pub invitee_peer_id: String,
}

pub trait InviteLifecycleHandler: Send + Sync {
    fn prepare_payload<'a>(
        &'a self,
        ctx: &'a InviteAcceptanceContext,
    ) -> Pin<Box<dyn Future<Output = Result<InvitePayload, InviteError>> + Send + 'a>>;

    fn commit_acceptance<'a>(
        &'a self,
        ctx: &'a InviteAcceptanceContext,
    ) -> Pin<Box<dyn Future<Output = Result<(), InviteError>> + Send + 'a>>;
}

pub trait InvitePersistenceHandler: Send + Sync {
    fn sync_invite(&self, passphrase: &str, invite: &PendingInvite) -> Result<(), InviteError>;
    fn delete_invite(&self, invite_id: &str) -> Result<(), InviteError>;
}

/// Owner-side invite handler. Implements `iroh::protocol::ProtocolHandler`
/// to accept incoming invite connections and run the SPAKE2 handshake.
pub struct InviteHandler {
    /// Active pending invites, keyed by passphrase.
    pending: Arc<DashMap<String, PendingInvite>>,
    /// Channel to notify when an invite is accepted (so the app can update the manifest).
    accepted_tx: tokio::sync::broadcast::Sender<InviteAccepted>,
    lifecycle: Option<Arc<dyn InviteLifecycleHandler>>,
    persistence: Option<Arc<dyn InvitePersistenceHandler>>,
    #[cfg(test)]
    completed_tx: tokio::sync::broadcast::Sender<()>,
}

impl std::fmt::Debug for InviteHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("InviteHandler")
            .field("pending_count", &self.pending.len())
            .finish()
    }
}

impl InviteHandler {
    pub fn new() -> Self {
        let (accepted_tx, _) = tokio::sync::broadcast::channel(64);
        #[cfg(test)]
        let (completed_tx, _) = tokio::sync::broadcast::channel(64);
        Self {
            pending: Arc::new(DashMap::new()),
            accepted_tx,
            lifecycle: None,
            persistence: None,
            #[cfg(test)]
            completed_tx,
        }
    }

    pub fn set_lifecycle_handler(&mut self, lifecycle: Arc<dyn InviteLifecycleHandler>) {
        self.lifecycle = Some(lifecycle);
    }

    pub fn set_persistence_handler(&mut self, persistence: Arc<dyn InvitePersistenceHandler>) {
        self.persistence = Some(persistence);
    }

    /// Subscribe to invite acceptance notifications.
    pub fn subscribe_accepted(&self) -> tokio::sync::broadcast::Receiver<InviteAccepted> {
        self.accepted_tx.subscribe()
    }

    #[cfg(test)]
    pub fn pending_snapshot(&self) -> Vec<(String, PendingInvite)> {
        self.pending
            .iter()
            .map(|entry| (entry.key().clone(), entry.value().clone()))
            .collect()
    }

    #[cfg(test)]
    pub fn subscribe_completed(&self) -> tokio::sync::broadcast::Receiver<()> {
        self.completed_tx.subscribe()
    }

    /// Register a pending invite. Called when the owner generates an invite code.
    pub fn add_pending(&self, passphrase: String, invite: PendingInvite) {
        if let Some(persistence) = &self.persistence {
            let _ = persistence.sync_invite(&passphrase, &invite);
        }
        self.pending.insert(passphrase, invite);
    }

    pub fn add_pending_checked(
        &self,
        passphrase: String,
        invite: PendingInvite,
    ) -> Result<(), InviteError> {
        if let Some(persistence) = &self.persistence {
            persistence.sync_invite(&passphrase, &invite)?;
        }
        self.pending.insert(passphrase, invite);
        Ok(())
    }

    /// Remove expired/exhausted invites.
    pub fn cleanup_expired(&self) {
        self.pending.retain(|_, invite| {
            if invite.is_expired() {
                if let Some(persistence) = &self.persistence {
                    let _ = persistence.delete_invite(&invite.invite_id);
                }
                return false;
            }

            if let InviteState::Reserved(reservation) = &invite.state {
                if Instant::now() >= reservation.timeout_at {
                    invite.state = InviteState::Open;
                    if let Some(persistence) = &self.persistence {
                        let _ = persistence.sync_invite(&invite.code.passphrase, &invite);
                    }
                }
            }

            if invite.is_exhausted() && !matches!(invite.state, InviteState::Reserved(_)) {
                if let Some(persistence) = &self.persistence {
                    let _ = persistence.delete_invite(&invite.invite_id);
                }
                return false;
            }

            true
        });
    }

    fn try_reserve_invite(
        &self,
        passphrase: &str,
        invitee_peer_id: &str,
        timeout_at: Instant,
    ) -> Result<InviteAcceptanceContext, InviteError> {
        let session_id = Uuid::new_v4().to_string();
        let mut invite = self.pending.get_mut(passphrase).ok_or(InviteError::Expired)?;

        if invite.is_expired() {
            drop(invite);
            self.pending.remove(passphrase);
            return Err(InviteError::Expired);
        }
        if invite.attempts > MAX_HANDSHAKE_ATTEMPTS {
            drop(invite);
            self.pending.remove(passphrase);
            return Err(InviteError::Exhausted);
        }
        if let InviteState::Reserved(reservation) = &invite.state {
            if Instant::now() >= reservation.timeout_at {
                invite.state = InviteState::Open;
                if let Some(persistence) = &self.persistence {
                    persistence.sync_invite(passphrase, &invite)?;
                }
            }
        }
        if !invite.is_available() {
            return Err(InviteError::Unavailable);
        }

        invite.attempts += 1;
        if invite.attempts > MAX_HANDSHAKE_ATTEMPTS {
            drop(invite);
            self.pending.remove(passphrase);
            return Err(InviteError::Exhausted);
        }

        invite.state = InviteState::Reserved(InviteReservation {
            session_id: session_id.clone(),
            invitee_peer_id: invitee_peer_id.to_string(),
            reserved_at: Instant::now(),
            timeout_at,
            phase: InviteSessionPhase::Reserved,
        });

        if let Some(persistence) = &self.persistence {
            if let Err(err) = persistence.sync_invite(passphrase, &invite) {
                invite.state = InviteState::Open;
                return Err(err);
            }
        }

        Ok(InviteAcceptanceContext {
            invite_id: invite.invite_id.clone(),
            session_id,
            passphrase: passphrase.to_string(),
            project_name: invite.project_name.clone(),
            project_id: invite.project_id.clone(),
            role: invite.invite_role.clone(),
            invitee_peer_id: invitee_peer_id.to_string(),
        })
    }

    fn set_reservation_phase(
        &self,
        passphrase: &str,
        session_id: &str,
        phase: InviteSessionPhase,
    ) -> Result<(), InviteError> {
        let mut invite = self.pending.get_mut(passphrase).ok_or(InviteError::Expired)?;
        match &mut invite.state {
            InviteState::Reserved(reservation) if reservation.session_id == session_id => {
                if Instant::now() >= reservation.timeout_at {
                    invite.state = InviteState::Open;
                    return Err(InviteError::Expired);
                }
                let previous = reservation.phase.clone();
                reservation.phase = phase;
                if let Some(persistence) = &self.persistence {
                    if let Err(err) = persistence.sync_invite(passphrase, &invite) {
                        if let InviteState::Reserved(reservation) = &mut invite.state {
                            reservation.phase = previous;
                        }
                        return Err(err);
                    }
                }
                Ok(())
            }
            InviteState::Reserved(_)
            | InviteState::CommittedPendingAck(_)
            | InviteState::Consumed(_) => Err(InviteError::Unavailable),
            InviteState::Open => Err(InviteError::InvalidState),
        }
    }

    fn release_reservation(&self, passphrase: &str, session_id: &str) -> Result<(), InviteError> {
        if let Some(mut invite) = self.pending.get_mut(passphrase) {
            if matches!(
                &invite.state,
                InviteState::Reserved(reservation) if reservation.session_id == session_id
            ) {
                let previous = invite.state.clone();
                invite.state = InviteState::Open;
                if let Some(persistence) = &self.persistence {
                    if let Err(err) = persistence.sync_invite(passphrase, &invite) {
                        invite.state = previous;
                        return Err(err);
                    }
                }
            }
        }
        Ok(())
    }

    fn mark_consumed(&self, passphrase: &str, session_id: &str, invitee_peer_id: &str) -> Result<(), InviteError> {
        if let Some(mut invite) = self.pending.get_mut(passphrase) {
            if matches!(
                &invite.state,
                InviteState::CommittedPendingAck(committed) if committed.session_id == session_id
            ) {
                let previous = invite.state.clone();
                invite.state = InviteState::Consumed(InviteConsumed {
                    session_id: session_id.to_string(),
                    invitee_peer_id: invitee_peer_id.to_string(),
                    consumed_at: Instant::now(),
                });
                if let Some(persistence) = &self.persistence {
                    if let Err(err) = persistence.sync_invite(passphrase, &invite) {
                        invite.state = previous;
                        return Err(err);
                    }
                }
            }
        }
        Ok(())
    }

    fn mark_committed_pending_ack(
        &self,
        passphrase: &str,
        session_id: &str,
        invitee_peer_id: &str,
    ) -> Result<(), InviteError> {
        let mut invite = self.pending.get_mut(passphrase).ok_or(InviteError::Expired)?;
        match &invite.state {
            InviteState::Reserved(reservation) if reservation.session_id == session_id => {
                let previous = invite.state.clone();
                invite.state = InviteState::CommittedPendingAck(InviteCommittedPendingAck {
                    session_id: session_id.to_string(),
                    invitee_peer_id: invitee_peer_id.to_string(),
                    committed_at: Instant::now(),
                });
                if let Some(persistence) = &self.persistence {
                    if let Err(err) = persistence.sync_invite(passphrase, &invite) {
                        invite.state = previous;
                        return Err(err);
                    }
                }
                Ok(())
            }
            InviteState::CommittedPendingAck(_) | InviteState::Consumed(_) => {
                Err(InviteError::Unavailable)
            }
            InviteState::Open | InviteState::Reserved(_) => Err(InviteError::InvalidState),
        }
    }

    /// Handle an incoming invite connection from an invitee using SPAKE2.
    ///
    /// Protocol:
    /// 1. Read invitee's SPAKE2 message (33 bytes for Ed25519Group)
    /// 2. Try each pending invite's passphrase:
    ///    - Start owner-side SPAKE2 with that passphrase
    ///    - Send owner's SPAKE2 message
    ///    - Finish handshake to derive shared key
    ///    - Send encrypted payload under shared key
    ///    - If decryption succeeds on the invitee side, the handshake worked
    /// 3. The invitee cannot distinguish wrong-passphrase from right-passphrase
    ///    until they try to decrypt (authenticated encryption).
    /// 4. After sending the payload the owner waits for a one-byte ACK from the
    ///    invitee proving the payload decrypted successfully.
    /// 5. The owner then commits acceptance and sends a one-byte final status
    ///    (`1` = committed, `0` = failed). The invitee only treats the join as
    ///    successful after that final owner confirmation arrives.
    async fn handle_connection(&self, connection: Connection) -> Result<(), InviteError> {
        let deadline = Instant::now() + INVITE_HANDSHAKE_TIMEOUT;
        self.handle_connection_inner(connection, deadline).await
    }

    async fn handle_connection_inner(
        &self,
        connection: Connection,
        deadline: Instant,
    ) -> Result<(), InviteError> {
        let deadline_tokio = tokio::time::Instant::from_std(deadline);
        let (mut send, mut recv) = tokio::time::timeout_at(deadline_tokio, connection.accept_bi())
            .await
            .map_err(|_| {
                self.cleanup_expired();
                InviteError::Connection("accept stream timed out".into())
            })?
            .map_err(|e| {
                self.cleanup_expired();
                InviteError::Connection(format!("accept stream: {e}"))
            })?;

        // Step 1: Read invitee's SPAKE2 message
        let mut invitee_msg_len_buf = [0u8; 4];
        tokio::time::timeout_at(deadline_tokio, recv.read_exact(&mut invitee_msg_len_buf))
            .await
            .map_err(|_| {
                self.cleanup_expired();
                InviteError::Connection("read spake2 len timed out".into())
            })?
            .map_err(|e| {
                self.cleanup_expired();
                InviteError::Connection(format!("read spake2 len: {e}"))
            })?;
        let invitee_msg_len = u32::from_be_bytes(invitee_msg_len_buf) as usize;
        if invitee_msg_len > 256 {
            return Err(InviteError::InvalidPayload);
        }
        let mut invitee_msg = vec![0u8; invitee_msg_len];
        tokio::time::timeout_at(deadline_tokio, recv.read_exact(&mut invitee_msg))
            .await
            .map_err(|_| {
                self.cleanup_expired();
                InviteError::Connection("read spake2 msg timed out".into())
            })?
            .map_err(|e| {
                self.cleanup_expired();
                InviteError::Connection(format!("read spake2 msg: {e}"))
            })?;

        // Step 2: Try each pending invite's passphrase with SPAKE2
        self.cleanup_expired();

        let pending_count = self.pending.len();
        log::info!(
            "Invite handler: received SPAKE2 from invitee, checking against {pending_count} pending invite(s)"
        );

        let mut matched: Option<(String, Vec<u8>)> = None; // (passphrase, shared_key)

        for entry in self.pending.iter() {
            let passphrase = entry.key();
            let invite = entry.value();

            if invite.is_expired() {
                log::debug!("Invite handler: skipping expired invite for project '{}'", invite.project_name);
                continue;
            }
            if invite.is_exhausted() {
                log::debug!("Invite handler: skipping exhausted invite for project '{}'", invite.project_name);
                continue;
            }
            let resumable_for_peer = matches!(
                &invite.state,
                InviteState::CommittedPendingAck(committed)
                    if committed.invitee_peer_id == connection.remote_id().to_string()
            );
            if !invite.is_available() && !resumable_for_peer {
                log::debug!(
                    "Invite handler: skipping unavailable invite for project '{}'",
                    invite.project_name
                );
                continue;
            }

            let (owner_state, owner_msg) = start_owner_handshake(passphrase);

            // Try to complete the handshake
            if let Ok(mut shared_key) = finish_handshake(owner_state, &invitee_msg) {
                // Send our SPAKE2 message to the invitee
                let len = (owner_msg.len() as u32).to_be_bytes();
                tokio::time::timeout_at(deadline_tokio, send.write_all(&len))
                    .await
                    .map_err(|_| {
                        self.cleanup_expired();
                        InviteError::Connection("send spake2 len timed out".into())
                    })?
                    .map_err(|e| {
                        self.cleanup_expired();
                        InviteError::Connection(format!("send spake2 len: {e}"))
                    })?;
                tokio::time::timeout_at(deadline_tokio, send.write_all(&owner_msg))
                    .await
                    .map_err(|_| {
                        self.cleanup_expired();
                        InviteError::Connection("send spake2 msg timed out".into())
                    })?
                    .map_err(|e| {
                        self.cleanup_expired();
                        InviteError::Connection(format!("send spake2 msg: {e}"))
                    })?;

                matched = Some((passphrase.clone(), shared_key.clone()));
                shared_key.zeroize();
                break;
            }
        }

        let (passphrase, mut shared_key) = match matched {
            Some(m) => {
                log::info!("Invite handler: SPAKE2 passphrase matched");
                m
            }
            None => {
                log::error!(
                    "Invite handler: SPAKE2 handshake failed — no matching passphrase among {pending_count} pending invite(s). \
                     The invitee sent a code that doesn't match any active invite."
                );
                return Err(InviteError::VerificationFailed);
            }
        };

        if let Some(invite) = self.pending.get(&passphrase) {
            if let InviteState::CommittedPendingAck(committed) = &invite.state {
                if committed.invitee_peer_id == connection.remote_id().to_string() {
                    shared_key.zeroize();
                    send.write_all(&[1])
                        .await
                        .map_err(|e| InviteError::Connection(format!("send resumed final status: {e}")))?;
                    send.flush()
                        .await
                        .map_err(|e| InviteError::Connection(format!("flush resumed final status: {e}")))?;

                    let mut final_ack = [0u8; 1];
                    match tokio::time::timeout_at(deadline_tokio, recv.read_exact(&mut final_ack)).await {
                        Ok(Ok(_)) if final_ack[0] == 1 => {
                            self.mark_consumed(&passphrase, &committed.session_id, &committed.invitee_peer_id)?;
                        }
                        _ => {
                            log::warn!(
                                "Committed invite for project {} resumed without applied ack",
                                invite.project_name
                            );
                        }
                    }
                    let _ = send.finish();
                    return Ok(());
                }

                shared_key.zeroize();
                return Err(InviteError::Unavailable);
            }
        }

        let ctx = match self.try_reserve_invite(
            &passphrase,
            &connection.remote_id().to_string(),
            deadline,
        ) {
            Ok(ctx) => ctx,
            Err(err) => {
                shared_key.zeroize();
                return Err(err);
            }
        };

        // Step 3: Build the payload. In production this comes from the lifecycle
        // handler so it can be prepared from current app state rather than the
        // invite creation snapshot.
        let payload = if let Some(lifecycle) = &self.lifecycle {
            match tokio::time::timeout_at(deadline_tokio, lifecycle.prepare_payload(&ctx)).await {
                Ok(Ok(payload)) => payload,
                Ok(Err(err)) => {
                    self.release_reservation(&ctx.passphrase, &ctx.session_id)?;
                    shared_key.zeroize();
                    return Err(err);
                }
                Err(_) => {
                    self.release_reservation(&ctx.passphrase, &ctx.session_id)?;
                    shared_key.zeroize();
                    return Err(InviteError::Connection("prepare payload timed out".into()));
                }
            }
        } else {
            #[cfg(not(test))]
            {
                return Err(InviteError::Lifecycle(
                    "missing invite lifecycle handler".into(),
                ));
            }

            #[cfg(test)]
            {
            let invite = self.pending.get(&passphrase).ok_or(InviteError::Expired)?;
            let manifest_hex = invite
                .manifest_data
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<String>();
            let owner_x25519_public_hex = invite
                .owner_x25519_public
                .map(|pk| pk.iter().map(|b| format!("{:02x}", b)).collect::<String>())
                .unwrap_or_default();

            let epoch_key_hex = invite
                .epoch_key
                .as_ref()
                .map(|k| k.iter().map(|b| format!("{:02x}", b)).collect::<String>())
                .unwrap_or_default();

            InvitePayload {
                invite_id: invite.invite_id.clone(),
                session_id: ctx.session_id.clone(),
                project_id: invite.project_id.clone(),
                project_name: invite.project_name.clone(),
                role: invite.invite_role.clone(),
                manifest_hex,
                owner_x25519_public_hex,
                epoch_key_hex,
                epoch: invite.current_epoch,
            }
            }
        };
        self.set_reservation_phase(&ctx.passphrase, &ctx.session_id, InviteSessionPhase::PayloadPrepared)?;

        let payload_json =
            serde_json::to_vec(&payload).map_err(|e| InviteError::Serde(e.to_string()))?;
        let encrypted = encrypt_payload(&shared_key, &payload_json)?;
        shared_key.zeroize();

        // Send length-prefixed encrypted payload
        let len = (encrypted.len() as u32).to_be_bytes();
        tokio::time::timeout_at(deadline_tokio, send.write_all(&len))
            .await
            .map_err(|_| {
                let _ = self.release_reservation(&ctx.passphrase, &ctx.session_id);
                InviteError::Connection("send payload length timed out".into())
            })?
            .map_err(|e| {
                let _ = self.release_reservation(&ctx.passphrase, &ctx.session_id);
                InviteError::Connection(format!("send length: {e}"))
            })?;
        tokio::time::timeout_at(deadline_tokio, send.write_all(&encrypted))
            .await
            .map_err(|_| {
                let _ = self.release_reservation(&ctx.passphrase, &ctx.session_id);
                InviteError::Connection("send payload timed out".into())
            })?
            .map_err(|e| {
                let _ = self.release_reservation(&ctx.passphrase, &ctx.session_id);
                InviteError::Connection(format!("send payload: {e}"))
            })?;
        self.set_reservation_phase(&ctx.passphrase, &ctx.session_id, InviteSessionPhase::PayloadSent)?;
        self.set_reservation_phase(&ctx.passphrase, &ctx.session_id, InviteSessionPhase::AwaitingPreparedAck)?;

        let mut prepared_ack = [0u8; 1];
        tokio::time::timeout_at(deadline_tokio, recv.read_exact(&mut prepared_ack))
            .await
            .map_err(|_| {
                let _ = self.release_reservation(&ctx.passphrase, &ctx.session_id);
                InviteError::Connection("read invitee prepared ack timed out".into())
            })?
            .map_err(|e| {
                let _ = self.release_reservation(&ctx.passphrase, &ctx.session_id);
                InviteError::Connection(format!("read invitee prepared ack: {e}"))
            })?;
        if prepared_ack[0] != 1 {
            self.release_reservation(&ctx.passphrase, &ctx.session_id)?;
            return Err(InviteError::VerificationFailed);
        }
        self.set_reservation_phase(&ctx.passphrase, &ctx.session_id, InviteSessionPhase::PreparedAckReceived)?;

        if let Some(lifecycle) = &self.lifecycle {
            let commit_result = tokio::time::timeout_at(deadline_tokio, lifecycle.commit_acceptance(&ctx)).await;
            if let Err(_) = commit_result {
                self.release_reservation(&ctx.passphrase, &ctx.session_id)?;
                let _ = send.write_all(&[0]).await;
                let _ = send.flush().await;
                let _ = send.finish();
                return Err(InviteError::Connection("owner commit timed out".into()));
            }
            if let Err(err) = commit_result.expect("checked above") {
                self.release_reservation(&ctx.passphrase, &ctx.session_id)?;
                let _ = send.write_all(&[0]).await;
                let _ = send.flush().await;
                let _ = send.finish();
                return Err(err);
            }
        }
        self.set_reservation_phase(&ctx.passphrase, &ctx.session_id, InviteSessionPhase::Committed)?;
        self.mark_committed_pending_ack(&ctx.passphrase, &ctx.session_id, &ctx.invitee_peer_id)?;

        send.write_all(&[1])
            .await
            .map_err(|e| InviteError::Connection(format!("send final status: {e}")))?;
        send.flush()
            .await
            .map_err(|e| InviteError::Connection(format!("flush final status: {e}")))?;

        let mut final_ack = [0u8; 1];
        match tokio::time::timeout_at(deadline_tokio, recv.read_exact(&mut final_ack)).await {
            Ok(Ok(_)) if final_ack[0] == 1 => {
                self.mark_consumed(&ctx.passphrase, &ctx.session_id, &ctx.invitee_peer_id)?;

                let _ = self.accepted_tx.send(InviteAccepted {
                    project_name: payload.project_name.clone(),
                    invitee_peer_id: ctx.invitee_peer_id.clone(),
                    role: payload.role.clone(),
                });
            }
            _ => {
                log::warn!(
                    "Invite accepted for project {} committed but invitee confirmation was not received",
                    payload.project_name
                );
            }
        }
        let _ = send.finish();

        log::info!(
            "Invite accepted for project {} by peer {invitee_peer_id}",
            payload.project_name,
            invitee_peer_id = ctx.invitee_peer_id
        );
        Ok(())
    }
}

impl Default for InviteHandler {
    fn default() -> Self {
        Self::new()
    }
}

impl iroh::protocol::ProtocolHandler for InviteHandler {
    fn accept(
        &self,
        connection: Connection,
    ) -> impl std::future::Future<Output = Result<(), AcceptError>> + Send {
        let handler = InviteHandler {
            pending: Arc::clone(&self.pending),
            accepted_tx: self.accepted_tx.clone(),
            lifecycle: self.lifecycle.clone(),
            persistence: self.persistence.clone(),
            #[cfg(test)]
            completed_tx: self.completed_tx.clone(),
        };

        async move {
            let remote_id = connection.remote_id();
            log::info!("Invite handler: incoming connection from peer {remote_id}");
            let result = handler.handle_connection(connection).await;
            #[cfg(test)]
            let _ = handler.completed_tx.send(());
            if let Err(e) = result {
                log::error!("Invite handler: connection from {remote_id} failed: {e}");
            }
            Ok(())
        }
    }
}

/// Errors in the invite flow.
#[derive(Debug, thiserror::Error)]
pub enum InviteError {
    #[error("SPAKE2 verification failed — wrong passphrase")]
    VerificationFailed,

    #[error("Encryption failed")]
    CryptoError,

    #[error("Decryption failed — wrong key or tampered data")]
    DecryptionFailed,

    #[error("Invalid payload format")]
    InvalidPayload,

    #[error("Invite expired")]
    Expired,

    #[error("Too many handshake attempts")]
    Exhausted,

    #[error("Invite is already reserved or consumed")]
    Unavailable,

    #[error("Invite is in an invalid state for this operation")]
    InvalidState,

    #[error("Connection error: {0}")]
    Connection(String),

    #[error("Serialization error: {0}")]
    Serde(String),

    #[error("Lifecycle error: {0}")]
    Lifecycle(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    use std::time::Duration;

    use iroh::{Endpoint, RelayMode, address_lookup::memory::MemoryLookup, endpoint::presets};
    use iroh::protocol::Router;
    use tokio::io::AsyncWriteExt;

    struct InviteTestHarness {
        owner_ep: Endpoint,
        invitee_ep: Endpoint,
        owner_router: iroh::protocol::Router,
        pending_map: Arc<DashMap<String, PendingInvite>>,
        completed_rx: tokio::sync::Mutex<tokio::sync::broadcast::Receiver<()>>,
    }

    impl InviteTestHarness {
        async fn new(
            invites: Vec<(String, PendingInvite)>,
            lifecycle: Option<Arc<dyn InviteLifecycleHandler>>,
        ) -> Self {
            let owner_lookup = MemoryLookup::new();
            let owner_ep = Endpoint::builder(presets::N0)
                .relay_mode(RelayMode::Disabled)
                .address_lookup(owner_lookup.clone())
                .bind()
                .await
                .expect("owner endpoint bind");

            let mut owner_handler = InviteHandler::new();
            if let Some(lifecycle) = lifecycle {
                owner_handler.set_lifecycle_handler(lifecycle);
            }
            let pending_map = owner_handler.pending.clone();
            let completed_rx = owner_handler.subscribe_completed();
            for (passphrase, invite) in invites {
                owner_handler.add_pending(passphrase, invite);
            }

            let owner_router = Router::builder(owner_ep.clone())
                .accept(INVITE_ALPN, owner_handler)
                .spawn();

            let owner_addr = owner_ep.addr();
            owner_lookup.add_endpoint_info(owner_addr.clone());

            let invitee_lookup = MemoryLookup::new();
            invitee_lookup.add_endpoint_info(owner_addr);
            let invitee_ep = Endpoint::builder(presets::N0)
                .relay_mode(RelayMode::Disabled)
                .address_lookup(invitee_lookup)
                .bind()
                .await
                .expect("invitee endpoint bind");

            Self {
                owner_ep,
                invitee_ep,
                owner_router,
                pending_map,
                completed_rx: tokio::sync::Mutex::new(completed_rx),
            }
        }

        async fn run_invitee(
            &self,
            invitee_passphrase: &str,
            ack_byte: Option<u8>,
        ) -> Result<InvitePayload, String> {
            self.run_invitee_with_behavior(
                invitee_passphrase,
                ack_byte,
                Duration::from_millis(0),
                true,
            )
                .await
        }

        async fn run_invitee_with_behavior(
            &self,
            invitee_passphrase: &str,
            ack_byte: Option<u8>,
            ack_delay: Duration,
            send_applied_ack: bool,
        ) -> Result<InvitePayload, String> {
            let connection = self
                .invitee_ep
                .connect(self.owner_ep.id(), INVITE_ALPN)
                .await
                .map_err(|e| format!("connect: {e}"))?;

            let (mut send, mut recv) = connection
                .open_bi()
                .await
                .map_err(|e| format!("open_bi: {e}"))?;

            let (invitee_state, invitee_msg) = start_invitee_handshake(invitee_passphrase);
            let len = (invitee_msg.len() as u32).to_be_bytes();
            send.write_all(&len)
                .await
                .map_err(|e| format!("send len: {e}"))?;
            send.write_all(&invitee_msg)
                .await
                .map_err(|e| format!("send msg: {e}"))?;

            let mut owner_msg_len_buf = [0u8; 4];
            recv.read_exact(&mut owner_msg_len_buf)
                .await
                .map_err(|e| format!("read owner len: {e}"))?;
            let owner_msg_len = u32::from_be_bytes(owner_msg_len_buf) as usize;
            let mut owner_msg = vec![0u8; owner_msg_len];
            recv.read_exact(&mut owner_msg)
                .await
                .map_err(|e| format!("read owner msg: {e}"))?;

            let shared_key = finish_handshake(invitee_state, &owner_msg)
                .map_err(|e| format!("finish handshake: {e}"))?;

            let mut len_buf = [0u8; 4];
            recv.read_exact(&mut len_buf)
                .await
                .map_err(|e| format!("read payload len: {e}"))?;
            let payload_len = u32::from_be_bytes(len_buf) as usize;
            let mut encrypted = vec![0u8; payload_len];
            recv.read_exact(&mut encrypted)
                .await
                .map_err(|e| format!("read payload: {e}"))?;

            let plaintext = decrypt_payload(&shared_key, &encrypted)
                .map_err(|e| format!("decrypt payload: {e}"))?;
            let payload: InvitePayload = serde_json::from_slice(&plaintext)
                .map_err(|e| format!("deserialize payload: {e}"))?;

            if let Some(ack_byte) = ack_byte {
                if !ack_delay.is_zero() {
                    tokio::time::sleep(ack_delay).await;
                }
                send.write_all(&[ack_byte])
                    .await
                    .map_err(|e| format!("send ack: {e}"))?;
                send.flush()
                    .await
                    .map_err(|e| format!("flush ack: {e}"))?;
                if ack_byte == 1 {
                    let mut final_status = [0u8; 1];
                    recv.read_exact(&mut final_status)
                        .await
                        .map_err(|e| format!("read final status: {e}"))?;
                    if final_status[0] != 1 {
                        return Err("owner failed to finalize invite acceptance".into());
                    }
                    if send_applied_ack {
                        send.write_all(&[1])
                            .await
                            .map_err(|e| format!("send final ack: {e}"))?;
                        send.flush()
                            .await
                            .map_err(|e| format!("flush final ack: {e}"))?;
                    }
                }
                let _ = send.finish();
            }

            Ok(payload)
        }

        async fn shutdown(self) {
            self.owner_router.shutdown().await.ok();
            self.owner_ep.close().await;
            self.invitee_ep.close().await;
        }

        async fn wait_for_invite_state<F>(&self, passphrase: &str, predicate: F)
        where
            F: Fn(&InviteState) -> bool,
        {
            tokio::time::timeout(Duration::from_secs(15), async {
                loop {
                    let matches = self
                        .pending_map
                        .get(passphrase)
                        .map(|invite| predicate(&invite.state))
                        .unwrap_or(false);
                    if matches {
                        break;
                    }
                    tokio::task::yield_now().await;
                }
            })
            .await
            .expect("timed out waiting for invite lifecycle state");
        }

        async fn wait_for_connection_completion(&self) {
            let mut rx = self.completed_rx.lock().await;
            tokio::time::timeout(Duration::from_secs(15), rx.recv())
                .await
                .expect("timed out waiting for connection completion")
                .expect("completion channel closed");
        }
    }

    fn make_pending_invite(
        owner_peer_id: String,
        passphrase: &str,
        project_name: &str,
        project_id: &str,
        manifest_data: Vec<u8>,
    ) -> PendingInvite {
        PendingInvite {
            invite_id: Uuid::new_v4().to_string(),
            code: InviteCode {
                passphrase: passphrase.to_string(),
                peer_id: owner_peer_id,
                expires_at: chrono::Utc::now() + chrono::Duration::minutes(10),
            },
            created_at: Instant::now(),
            attempts: 0,
            project_name: project_name.to_string(),
            project_id: project_id.to_string(),
            invite_role: "editor".to_string(),
            state: InviteState::Open,
            #[cfg(test)]
            manifest_data,
            #[cfg(test)]
            owner_x25519_public: None,
            #[cfg(test)]
            epoch_key: None,
            #[cfg(test)]
            current_epoch: 0,
        }
    }

    struct MockLifecycleHandler {
        payload: InvitePayload,
        commit_error: Option<String>,
    }

    impl InviteLifecycleHandler for MockLifecycleHandler {
        fn prepare_payload<'a>(
            &'a self,
            _ctx: &'a InviteAcceptanceContext,
        ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<InvitePayload, InviteError>> + Send + 'a>> {
            Box::pin(async move { Ok(self.payload.clone()) })
        }

        fn commit_acceptance<'a>(
            &'a self,
            _ctx: &'a InviteAcceptanceContext,
        ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), InviteError>> + Send + 'a>> {
            Box::pin(async move {
                match &self.commit_error {
                    Some(err) => Err(InviteError::Lifecycle(err.clone())),
                    None => Ok(()),
                }
            })
        }
    }

    // ── End-to-end invite flow test ────────────────────────────────────────
    //
    // Spins up two real iroh endpoints in-process (no relay, direct loopback
    // connection via MemoryLookup so there are no network dependencies) and
    // runs the complete invite handshake:
    //
    //   owner:   InviteHandler registered via Router, PendingInvite inserted
    //   invitee: connect → SPAKE2 → read payload → send.finish()
    //   owner:   recv.read_to_end() unblocks → invite consumed
    //
    // This test catches regression of Bug 1 (owner drops connection before
    // invitee reads payload) and validates the full wire protocol end-to-end.
    #[tokio::test]
    async fn test_invite_end_to_end() {
        let passphrase = "tiger-marble-ocean-violet-canyon-frost";

        // Build a large fake manifest payload so the invitee is definitely still
        // reading when the owner would regressively drop the connection.
        let fake_manifest_bytes = vec![0xAB; 64 * 1024];
        let fake_manifest_hex: String = fake_manifest_bytes
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect();

        let harness = InviteTestHarness::new(vec![(
            passphrase.to_string(),
            make_pending_invite(
                "owner-peer".to_string(),
                passphrase,
                "test-project",
                "test-uuid-1234",
                fake_manifest_bytes.clone(),
            ),
        )], None)
        .await;

        let expected_manifest_hex = fake_manifest_hex.clone();
        let invitee_result = tokio::time::timeout(Duration::from_secs(10), async {
            harness.run_invitee(passphrase, Some(1)).await
        })
        .await
        .expect("invitee timed out")
        .expect("invitee flow failed");

        // ── Assert payload contents ───────────────────────────────────────
        assert_eq!(invitee_result.project_name, "test-project");
        assert_eq!(invitee_result.project_id, "test-uuid-1234");
        assert_eq!(invitee_result.role, "editor");
        assert_eq!(invitee_result.manifest_hex, expected_manifest_hex);

        harness.wait_for_connection_completion().await;
        assert!(matches!(
            harness.pending_map.get(passphrase).as_deref().map(|invite| &invite.state),
            Some(InviteState::Consumed(_) | InviteState::CommittedPendingAck(_))
        ));

        // The dedicated malformed/no-ACK/wrong-passphrase tests assert the opposite side:
        // after a single failed attempt, the invite remains pending and usable.
        // Together these tests pin the current consumption behavior for the refactor.
        assert!(
            !matches!(
                harness.pending_map.get(passphrase).as_deref().map(|invite| &invite.state),
                Some(InviteState::Open)
            ),
            "successful invite acceptance should not reopen the one-time code"
        );

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_wrong_passphrase_does_not_consume_invite() {
        let passphrase = "correct-horse-battery-staple-ocean-frost";
        let wrong_passphrase = "wrong-horse-battery-staple-ocean-frost";
        let project_name = "wrong-passphrase-project";
        let harness = InviteTestHarness::new(vec![(
            passphrase.to_string(),
            make_pending_invite(
                "owner-peer".to_string(),
                passphrase,
                project_name,
                "proj-wrong",
                vec![1; 128],
            ),
        )], None)
        .await;

        let result = harness.run_invitee(wrong_passphrase, None).await;
        assert!(result.is_err(), "wrong passphrase should fail to decrypt payload");

        harness.wait_for_connection_completion().await;
        assert!(matches!(
            harness.pending_map.get(passphrase).as_deref().map(|invite| &invite.state),
            Some(InviteState::Open)
        ));

        let retry = harness.run_invitee(passphrase, Some(1)).await;
        assert!(retry.is_ok(), "invite should still be usable after wrong passphrase");

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_invite_without_ack_is_not_consumed() {
        let passphrase = "invitee-disconnect-without-ack-ocean-frost";
        let harness = InviteTestHarness::new(vec![(
            passphrase.to_string(),
            make_pending_invite(
                "owner-peer".to_string(),
                passphrase,
                "no-ack-project",
                "proj-no-ack",
                vec![2; 256],
            ),
        )], None)
        .await;

        let result = harness.run_invitee(passphrase, None).await;
        assert!(result.is_ok(), "invitee should still be able to read payload before dropping");

        harness.wait_for_connection_completion().await;
        assert!(matches!(
            harness.pending_map.get(passphrase).as_deref().map(|invite| &invite.state),
            Some(InviteState::Open)
        ));

        let retry = harness.run_invitee(passphrase, Some(1)).await;
        assert!(retry.is_ok(), "invite should still be usable after a missing ACK");

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_malformed_ack_does_not_consume_invite() {
        let passphrase = "invitee-malformed-ack-ocean-frost-canyon";
        let harness = InviteTestHarness::new(vec![(
            passphrase.to_string(),
            make_pending_invite(
                "owner-peer".to_string(),
                passphrase,
                "bad-ack-project",
                "proj-bad-ack",
                vec![3; 256],
            ),
        )], None)
        .await;

        let result = harness.run_invitee(passphrase, Some(7)).await;
        assert!(result.is_ok(), "invitee can still read payload before sending bad ack");

        harness.wait_for_connection_completion().await;
        assert!(matches!(
            harness.pending_map.get(passphrase).as_deref().map(|invite| &invite.state),
            Some(InviteState::Open)
        ));

        let retry = harness.run_invitee(passphrase, Some(1)).await;
        assert!(retry.is_ok(), "invite should still be usable after malformed ACK");

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_lifecycle_prepare_payload_is_used() {
        let passphrase = "lifecycle-success-ocean-frost-canyon-marble";
        let lifecycle_payload = InvitePayload {
            invite_id: "lifecycle-invite-id".to_string(),
            session_id: "lifecycle-session-id".to_string(),
            project_id: "lifecycle-project-id".to_string(),
            project_name: "Lifecycle Project".to_string(),
            role: "viewer".to_string(),
            manifest_hex: "beef".to_string(),
            owner_x25519_public_hex: String::new(),
            epoch_key_hex: String::new(),
            epoch: 7,
        };
        let lifecycle = Arc::new(MockLifecycleHandler {
            payload: lifecycle_payload.clone(),
            commit_error: None,
        });
        let harness = InviteTestHarness::new(
            vec![(
                passphrase.to_string(),
                make_pending_invite(
                    "owner-peer".to_string(),
                    passphrase,
                    "snapshot-project",
                    "snapshot-project-id",
                    vec![4; 64],
                ),
            )],
            Some(lifecycle),
        )
        .await;

        let payload = harness
            .run_invitee(passphrase, Some(1))
            .await
            .expect("lifecycle invite should succeed");
        assert_eq!(payload.project_id, lifecycle_payload.project_id);
        assert_eq!(payload.project_name, lifecycle_payload.project_name);
        assert_eq!(payload.role, lifecycle_payload.role);
        assert_eq!(payload.manifest_hex, lifecycle_payload.manifest_hex);

        let second_attempt = harness.run_invitee(passphrase, Some(1)).await;
        assert!(
            second_attempt.is_err(),
            "lifecycle-backed invite should also reject stale code reuse"
        );

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_lifecycle_commit_failure_does_not_consume_invite() {
        let passphrase = "lifecycle-failure-ocean-frost-canyon-marble";
        let lifecycle = Arc::new(MockLifecycleHandler {
            payload: InvitePayload {
                invite_id: "lifecycle-invite-id".to_string(),
                session_id: "lifecycle-session-id".to_string(),
                project_id: "lifecycle-project-id".to_string(),
                project_name: "Lifecycle Project".to_string(),
                role: "editor".to_string(),
                manifest_hex: "cafe".to_string(),
                owner_x25519_public_hex: String::new(),
                epoch_key_hex: String::new(),
                epoch: 1,
            },
            commit_error: Some("commit failed".into()),
        });
        let harness = InviteTestHarness::new(
            vec![(
                passphrase.to_string(),
                make_pending_invite(
                    "owner-peer".to_string(),
                    passphrase,
                    "snapshot-project",
                    "snapshot-project-id",
                    vec![5; 64],
                ),
            )],
            Some(lifecycle),
        )
        .await;

        let result = harness.run_invitee(passphrase, Some(1)).await;
        assert!(result.is_err(), "invitee should fail if owner commit fails after ACK");
        harness.wait_for_connection_completion().await;
        harness
            .wait_for_invite_state(passphrase, |state| matches!(state, InviteState::Open))
            .await;

        let retry = harness.run_invitee(passphrase, Some(1)).await;
        assert!(retry.is_err(), "commit failure should remain reproducible until owner-side issue is fixed");

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_commit_without_applied_ack_leaves_committed_pending_ack() {
        let passphrase = "commit-no-applied-ack-ocean-frost";
        let harness = InviteTestHarness::new(
            vec![(
                passphrase.to_string(),
                make_pending_invite(
                    "owner-peer".to_string(),
                    passphrase,
                    "pending-ack-project",
                    "pending-ack-project-id",
                    vec![7; 128],
                ),
            )],
            None,
        )
        .await;

        let result = harness
            .run_invitee_with_behavior(passphrase, Some(1), Duration::from_millis(0), false)
            .await;
        assert!(result.is_ok(), "invitee should still receive commit result before disconnecting");

        harness
            .wait_for_invite_state(passphrase, |state| {
                matches!(state, InviteState::CommittedPendingAck(_))
            })
            .await;

        let retry = harness.run_invitee(passphrase, Some(1)).await;
        assert!(retry.is_err(), "committed invite must not reopen after missing applied ack");

        harness.shutdown().await;
    }

    #[tokio::test]
    async fn test_try_reserve_invite_is_atomic() {
        let handler = Arc::new(InviteHandler::new());
        let passphrase = "concurrent-acceptors-ocean-frost-canyon";
        handler.add_pending(
            passphrase.to_string(),
            make_pending_invite(
                "owner-peer".to_string(),
                passphrase,
                "race-project",
                "race-project-id",
                vec![6; 128],
            ),
        );

        let barrier = Arc::new(tokio::sync::Barrier::new(3));
        let handler_a = Arc::clone(&handler);
        let barrier_a = Arc::clone(&barrier);
        let contender_a = tokio::spawn(async move {
            barrier_a.wait().await;
            handler_a.try_reserve_invite(
                passphrase,
                "peer-one",
                Instant::now() + INVITE_HANDSHAKE_TIMEOUT,
            )
        });

        let handler_b = Arc::clone(&handler);
        let barrier_b = Arc::clone(&barrier);
        let contender_b = tokio::spawn(async move {
            barrier_b.wait().await;
            handler_b.try_reserve_invite(
                passphrase,
                "peer-two",
                Instant::now() + INVITE_HANDSHAKE_TIMEOUT,
            )
        });

        barrier.wait().await;
        let result_a = contender_a.await.unwrap();
        let result_b = contender_b.await.unwrap();

        let success_count = usize::from(result_a.is_ok()) + usize::from(result_b.is_ok());
        assert_eq!(success_count, 1, "only one contender may reserve the invite");

        let winner = result_a.or(result_b).unwrap();
        handler.release_reservation(passphrase, &winner.session_id).unwrap();
        let retry = handler
            .try_reserve_invite(
                passphrase,
                "peer-three",
                Instant::now() + INVITE_HANDSHAKE_TIMEOUT,
            )
            .unwrap();
        assert_eq!(retry.invitee_peer_id, "peer-three");
    }

    #[test]
    fn test_generate_passphrase() {
        let phrase = generate_passphrase(6);
        let words: Vec<&str> = phrase.split('-').collect();
        assert_eq!(words.len(), 6);
        for word in &words {
            assert!(!word.is_empty());
        }
    }

    #[test]
    fn test_passphrase_uniqueness() {
        let p1 = generate_passphrase(6);
        let p2 = generate_passphrase(6);
        assert_ne!(p1, p2);
    }

    #[test]
    fn test_spake2_handshake_matching_passphrase() {
        let passphrase = "tiger-marble-ocean-violet-canyon-frost";

        let (owner_state, owner_msg) = start_owner_handshake(passphrase);
        let (invitee_state, invitee_msg) = start_invitee_handshake(passphrase);

        let owner_key = finish_handshake(owner_state, &invitee_msg).unwrap();
        let invitee_key = finish_handshake(invitee_state, &owner_msg).unwrap();

        assert_eq!(owner_key, invitee_key, "Both sides should derive the same key");
        assert!(!owner_key.is_empty());
    }

    #[test]
    fn test_spake2_handshake_wrong_passphrase() {
        let (owner_state, _owner_msg) = start_owner_handshake("correct-phrase");
        let (_invitee_state, invitee_msg) = start_invitee_handshake("wrong-phrase");

        // SPAKE2 will "succeed" but derive different keys
        // The mismatch is detected when decryption fails
        let owner_key = finish_handshake(owner_state, &invitee_msg);
        // Note: spake2 crate may return Ok with a different key, or Err
        // depending on the implementation. Either way, the keys won't match.
        if let Ok(key) = owner_key {
            // If it succeeds, verify the key is different from a correct handshake
            let (correct_owner, _correct_owner_msg) = start_owner_handshake("correct-phrase");
            let (_correct_invitee, correct_invitee_msg) =
                start_invitee_handshake("correct-phrase");
            let correct_key = finish_handshake(correct_owner, &correct_invitee_msg).unwrap();
            assert_ne!(key, correct_key, "Wrong passphrase should produce different key");
        }
        // If Err, that's also correct behavior
    }

    #[test]
    fn test_sas_computation() {
        let key1 = vec![1u8; 32];
        let key2 = vec![2u8; 32];

        let sas1 = compute_sas(&key1);
        let sas2 = compute_sas(&key2);

        assert_eq!(sas1.len(), 4);
        assert_ne!(sas1, sas2);
        assert!(sas1.chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let key = vec![0x42u8; 32];
        let plaintext = b"Hello, this is secret project data!";

        let encrypted = encrypt_payload(&key, plaintext).unwrap();
        assert_ne!(encrypted, plaintext);

        let decrypted = decrypt_payload(&key, &encrypted).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_decrypt_with_wrong_key_fails() {
        let key1 = vec![0x42u8; 32];
        let key2 = vec![0x43u8; 32];

        let plaintext = b"secret data";
        let encrypted = encrypt_payload(&key1, plaintext).unwrap();

        let result = decrypt_payload(&key2, &encrypted);
        assert!(matches!(result, Err(InviteError::DecryptionFailed)));
    }

    #[test]
    fn test_decrypt_truncated_data_fails() {
        let result = decrypt_payload(&vec![0u8; 32], &[0u8; 10]);
        assert!(matches!(result, Err(InviteError::InvalidPayload)));
    }

    #[test]
    fn test_invite_code_serde() {
        let code = InviteCode {
            passphrase: "tiger-marble-ocean-violet-canyon-frost".to_string(),
            peer_id: "abc123".to_string(),
            expires_at: chrono::Utc::now() + chrono::Duration::minutes(10),
        };

        let json = serde_json::to_string(&code).unwrap();
        let decoded: InviteCode = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.passphrase, code.passphrase);
        assert_eq!(decoded.peer_id, code.peer_id);
    }

    #[test]
    fn test_invite_payload_serde() {
        let payload = InvitePayload {
            invite_id: "test-invite-id".to_string(),
            session_id: "test-session-id".to_string(),
            project_id: "test-uuid".to_string(),
            project_name: "My Project".to_string(),
            role: "editor".to_string(),
            manifest_hex: "deadbeef".to_string(),
            owner_x25519_public_hex: String::new(),
            epoch_key_hex: String::new(),
            epoch: 0,
        };

        let json = serde_json::to_string(&payload).unwrap();
        let decoded: InvitePayload = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.project_name, "My Project");
    }

    fn test_pending_invite() -> PendingInvite {
        PendingInvite {
            invite_id: Uuid::new_v4().to_string(),
            code: InviteCode {
                passphrase: "test".to_string(),
                peer_id: "id".to_string(),
                expires_at: chrono::Utc::now() + chrono::Duration::minutes(10),
            },
            created_at: Instant::now(),
            attempts: 0,
            project_name: "test".to_string(),
            project_id: "test-id".to_string(),
            state: InviteState::Open,
            manifest_data: vec![],
            invite_role: "editor".to_string(),
            owner_x25519_public: None,
            epoch_key: None,
            current_epoch: 0,
        }
    }

    #[test]
    fn test_pending_invite_expiry() {
        let mut invite = test_pending_invite();
        invite.code.expires_at = chrono::Utc::now() - chrono::Duration::seconds(1);
        assert!(invite.is_expired());
    }

    #[test]
    fn test_pending_invite_not_expired() {
        let invite = test_pending_invite();
        assert!(!invite.is_expired());
    }

    #[test]
    fn test_pending_invite_exhausted() {
        let mut invite = test_pending_invite();
        invite.attempts = 3;
        assert!(invite.is_exhausted());
    }
}
