//! Invite flow for securely sharing projects between peers.
//!
//! The invite code serves as a pre-shared secret. Both sides derive
//! an encryption key from the code using HKDF, then exchange a
//! challenge-response to prove they share the same code. After
//! verification, the Owner sends encrypted project metadata.
//!
//! Security properties:
//! - Transport is already E2E encrypted via iroh QUIC (protects against eavesdropping)
//! - The HKDF-derived key proves both sides know the invite code (prevents unauthorized joins)
//! - Random challenge-response prevents replay attacks
//! - TTL + attempt limits prevent brute force
//! - XChaCha20-Poly1305 encryption of payload provides authenticated encryption

use std::time::{Duration, Instant};

use chacha20poly1305::aead::{Aead, KeyInit};
use chacha20poly1305::XChaCha20Poly1305;
use hkdf::Hkdf;
use serde::{Deserialize, Serialize};
use sha2::Sha256;

/// ALPN for the invite protocol (separate from sync).
pub const INVITE_ALPN: &[u8] = b"/p2p-notes/invite/1";

/// Default TTL for invite codes.
pub const DEFAULT_INVITE_TTL: Duration = Duration::from_secs(10 * 60); // 10 minutes

/// Maximum handshake attempts per invite code.
pub const MAX_HANDSHAKE_ATTEMPTS: u32 = 3;

/// HKDF context for deriving the invite encryption key.
const HKDF_CONTEXT: &[u8] = b"p2p-notes/v1/invite-key-derivation";

/// HKDF context for deriving the challenge MAC key.
const HKDF_CHALLENGE_CONTEXT: &[u8] = b"p2p-notes/v1/invite-challenge";

/// An invite code generated by the project owner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InviteCode {
    /// The secret passphrase (e.g., "tiger-marble-ocean-violet-canyon-frost").
    pub passphrase: String,
    /// The owner's peer ID, so the invitee knows who to connect to.
    pub peer_id: String,
    /// When this invite expires (ISO 8601).
    pub expires_at: chrono::DateTime<chrono::Utc>,
}

/// Data sent from Owner to Invitee after successful handshake.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvitePayload {
    /// Project ID.
    pub project_id: String,
    /// Project name.
    pub project_name: String,
    /// Role assigned to the invitee ("editor" or "viewer").
    pub role: String,
    /// The full manifest binary (Automerge document), hex-encoded.
    pub manifest_hex: String,
}

/// Tracks an active invite on the Owner side.
pub struct PendingInvite {
    pub code: InviteCode,
    pub created_at: Instant,
    pub attempts: u32,
    pub project_name: String,
    pub project_id: String,
    /// Derived encryption key (from passphrase via HKDF).
    pub derived_key: [u8; 32],
    /// The serialized manifest binary to send to the invitee.
    pub manifest_data: Vec<u8>,
    /// Role to assign the invitee.
    pub invite_role: String,
}

impl PendingInvite {
    pub fn is_expired(&self) -> bool {
        self.created_at.elapsed() > DEFAULT_INVITE_TTL
    }

    pub fn is_exhausted(&self) -> bool {
        self.attempts >= MAX_HANDSHAKE_ATTEMPTS
    }
}

/// Derive a 32-byte encryption key from the passphrase using HKDF-SHA256.
pub fn derive_key_from_passphrase(passphrase: &str) -> [u8; 32] {
    let hk = Hkdf::<Sha256>::new(Some(HKDF_CONTEXT), passphrase.as_bytes());
    let mut key = [0u8; 32];
    hk.expand(HKDF_CONTEXT, &mut key)
        .expect("HKDF expand failed — output length is valid");
    key
}

/// Derive a challenge MAC key from the passphrase.
fn derive_challenge_key(passphrase: &str) -> [u8; 32] {
    let hk = Hkdf::<Sha256>::new(Some(HKDF_CHALLENGE_CONTEXT), passphrase.as_bytes());
    let mut key = [0u8; 32];
    hk.expand(HKDF_CHALLENGE_CONTEXT, &mut key)
        .expect("HKDF expand failed");
    key
}

/// Generate a challenge-response proof that we know the passphrase.
/// The challenge is a random nonce; the response is HMAC(challenge_key, nonce).
pub fn generate_challenge() -> [u8; 32] {
    let mut nonce = [0u8; 32];
    getrandom::fill(&mut nonce).expect("failed to generate random challenge");
    nonce
}

/// Compute the response to a challenge using the passphrase-derived key.
pub fn compute_challenge_response(passphrase: &str, challenge: &[u8; 32]) -> [u8; 32] {
    let challenge_key = derive_challenge_key(passphrase);
    // Simple HMAC-like construction: HKDF-expand(challenge_key, challenge)
    let hk = Hkdf::<Sha256>::new(Some(challenge), &challenge_key);
    let mut response = [0u8; 32];
    hk.expand(b"challenge-response", &mut response)
        .expect("HKDF expand failed");
    response
}

/// Verify a challenge response.
pub fn verify_challenge_response(
    passphrase: &str,
    challenge: &[u8; 32],
    response: &[u8; 32],
) -> bool {
    let expected = compute_challenge_response(passphrase, challenge);
    // Constant-time comparison
    expected
        .iter()
        .zip(response.iter())
        .fold(0u8, |acc, (a, b)| acc | (a ^ b))
        == 0
}

/// Generate a random passphrase of `n` words.
/// Each word gives 8 bits of entropy (256-word list), so 6 words = 48 bits.
pub fn generate_passphrase(word_count: usize) -> String {
    // Exactly 256 words for uniform 8-bit selection with no modulo bias.
    const WORDS: &[&str] = &[
        "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball", "band",
        "bank", "base", "bath", "bean", "bear", "beat", "been", "bell", "belt", "best", "bill",
        "bird", "bite", "blow", "blue", "boat", "body", "bomb", "bond", "bone", "book", "boot",
        "born", "boss", "both", "bowl", "bulk", "burn", "bush", "busy", "calm", "came", "camp",
        "card", "care", "case", "cash", "cast", "cave", "cell", "chat", "chip", "city", "clam",
        "clay", "clip", "club", "clue", "coal", "coat", "code", "coin", "cold", "cole", "come",
        "cook", "cool", "cope", "copy", "core", "cost", "crew", "crop", "crow", "cure", "curl",
        "cute", "dale", "dame", "damp", "dare", "dark", "data", "date", "dawn", "deal", "dear",
        "debt", "deep", "deer", "demo", "deny", "desk", "dial", "diet", "dirt", "dish", "disk",
        "dock", "does", "dome", "done", "door", "dose", "dove", "down", "draw", "drew", "drop",
        "drum", "dual", "duke", "dull", "dump", "dune", "dust", "duty", "each", "earn", "ease",
        "east", "easy", "edge", "else", "epic", "euro", "even", "ever", "evil", "exam", "exit",
        "face", "fact", "fail", "fair", "fall", "fame", "fang", "farm", "fast", "fate", "fear",
        "feed", "feel", "feet", "fell", "felt", "file", "fill", "film", "find", "fine", "fire",
        "firm", "fish", "fist", "five", "flag", "flat", "fled", "flew", "flip", "flow", "foam",
        "fold", "folk", "fond", "font", "food", "foot", "ford", "fore", "fork", "form", "fort",
        "foul", "four", "free", "from", "fuel", "full", "fund", "fury", "fuse", "gain", "gale",
        "game", "gang", "gate", "gave", "gaze", "gear", "gene", "gift", "girl", "give", "glad",
        "glow", "glue", "goat", "goes", "gold", "golf", "gone", "good", "grab", "gray", "grew",
        "grid", "grim", "grip", "grow", "gulf", "guru", "gust", "hack", "hail", "hair", "half",
        "hall", "halt", "hand", "hang", "hard", "harm", "hate", "have", "hawk", "haze", "head",
        "heal", "heap", "hear", "heat", "held", "help", "herb", "here", "hero", "hide", "high",
        "hike", "hill", "hint", "hire", "hold", "hole", "holy", "home", "hood", "hook", "hope",
        "horn", "host", "hour",
    ];
    // Compile-time assertion: exactly 256 words for uniform byte selection
    const _: () = assert!(
        WORDS.len() == 256,
        "word list must have exactly 256 entries for unbiased selection"
    );

    let mut words = Vec::with_capacity(word_count);
    let mut rand_bytes = vec![0u8; word_count];
    getrandom::fill(&mut rand_bytes).expect("failed to generate random bytes");

    for byte in rand_bytes {
        let idx = byte as usize % WORDS.len();
        words.push(WORDS[idx]);
    }

    words.join("-")
}

/// Encrypt a payload using XChaCha20-Poly1305 with the derived key.
pub fn encrypt_payload(key: &[u8; 32], plaintext: &[u8]) -> Result<Vec<u8>, InviteError> {
    let cipher_key = chacha20poly1305::Key::from_slice(key);
    let cipher = XChaCha20Poly1305::new(cipher_key);

    let mut nonce_bytes = [0u8; 24];
    getrandom::fill(&mut nonce_bytes).map_err(|_| InviteError::CryptoError)?;
    let nonce = chacha20poly1305::XNonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, plaintext)
        .map_err(|_| InviteError::CryptoError)?;

    let mut result = Vec::with_capacity(24 + ciphertext.len());
    result.extend_from_slice(&nonce_bytes);
    result.extend_from_slice(&ciphertext);
    Ok(result)
}

/// Decrypt a payload using XChaCha20-Poly1305 with the derived key.
pub fn decrypt_payload(key: &[u8; 32], data: &[u8]) -> Result<Vec<u8>, InviteError> {
    if data.len() < 24 {
        return Err(InviteError::InvalidPayload);
    }

    let cipher_key = chacha20poly1305::Key::from_slice(key);
    let cipher = XChaCha20Poly1305::new(cipher_key);

    let nonce = chacha20poly1305::XNonce::from_slice(&data[..24]);
    let ciphertext = &data[24..];

    cipher
        .decrypt(nonce, ciphertext)
        .map_err(|_| InviteError::DecryptionFailed)
}

// ── Owner-side Invite Handler ─────────────────────────────────────────

use std::sync::Arc;
use dashmap::DashMap;
use iroh::endpoint::Connection;
use iroh::protocol::AcceptError;

/// Owner-side invite handler. Implements `iroh::protocol::ProtocolHandler`
/// to accept incoming invite connections and run the handshake.
pub struct InviteHandler {
    /// Active pending invites, keyed by passphrase.
    pending: Arc<DashMap<String, PendingInvite>>,
}

impl std::fmt::Debug for InviteHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("InviteHandler")
            .field("pending_count", &self.pending.len())
            .finish()
    }
}

impl InviteHandler {
    pub fn new() -> Self {
        Self {
            pending: Arc::new(DashMap::new()),
        }
    }

    /// Register a pending invite. Called when the owner generates an invite code.
    pub fn add_pending(&self, passphrase: String, invite: PendingInvite) {
        self.pending.insert(passphrase, invite);
    }

    /// Remove expired/exhausted invites.
    pub fn cleanup_expired(&self) {
        self.pending.retain(|_, v| !v.is_expired() && !v.is_exhausted());
    }

    /// Handle an incoming invite connection from an invitee.
    async fn handle_connection(&self, connection: Connection) -> Result<(), InviteError> {
        let (mut send, mut recv) = connection
            .accept_bi()
            .await
            .map_err(|e| InviteError::Connection(format!("accept stream: {e}")))?;

        // Step 1: Read invitee's challenge
        let mut invitee_challenge = [0u8; 32];
        recv.read_exact(&mut invitee_challenge)
            .await
            .map_err(|e| InviteError::Connection(format!("read challenge: {e}")))?;

        // Step 2: Send our challenge
        let our_challenge = generate_challenge();
        send.write_all(&our_challenge)
            .await
            .map_err(|e| InviteError::Connection(format!("send challenge: {e}")))?;

        // Step 3: Read invitee's response to our challenge
        let mut invitee_response = [0u8; 32];
        recv.read_exact(&mut invitee_response)
            .await
            .map_err(|e| InviteError::Connection(format!("read response: {e}")))?;

        // Find the matching pending invite by trying each passphrase
        let mut matched_passphrase: Option<String> = None;
        for entry in self.pending.iter() {
            let passphrase = entry.key();
            if verify_challenge_response(passphrase, &our_challenge, &invitee_response) {
                matched_passphrase = Some(passphrase.clone());
                break;
            }
        }

        let passphrase = match matched_passphrase {
            Some(p) => p,
            None => {
                // Increment attempt counts for all pending invites (brute-force mitigation)
                for mut entry in self.pending.iter_mut() {
                    entry.value_mut().attempts += 1;
                }
                self.cleanup_expired();
                log::warn!("Invite handshake failed: no matching passphrase");
                return Err(InviteError::VerificationFailed);
            }
        };

        // Validate the invite is still valid
        {
            let mut invite = self
                .pending
                .get_mut(&passphrase)
                .ok_or(InviteError::Expired)?;
            invite.attempts += 1;
            if invite.is_expired() {
                drop(invite);
                self.pending.remove(&passphrase);
                return Err(InviteError::Expired);
            }
            if invite.is_exhausted() {
                drop(invite);
                self.pending.remove(&passphrase);
                return Err(InviteError::Exhausted);
            }
        }

        // Step 4: Send our response to invitee's challenge
        let our_response = compute_challenge_response(&passphrase, &invitee_challenge);
        send.write_all(&our_response)
            .await
            .map_err(|e| InviteError::Connection(format!("send response: {e}")))?;

        // Step 5: Send encrypted payload
        let derived_key = derive_key_from_passphrase(&passphrase);

        // Build the invite payload from the pending invite data
        let payload = {
            let invite = self.pending.get(&passphrase).ok_or(InviteError::Expired)?;
            let manifest_hex = invite
                .manifest_data
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<String>();
            InvitePayload {
                project_id: invite.project_id.clone(),
                project_name: invite.project_name.clone(),
                role: invite.invite_role.clone(),
                manifest_hex,
            }
        };

        let payload_json = serde_json::to_vec(&payload)
            .map_err(|e| InviteError::Serde(e.to_string()))?;
        let encrypted = encrypt_payload(&derived_key, &payload_json)?;

        // Send length-prefixed encrypted payload
        let len = (encrypted.len() as u32).to_be_bytes();
        send.write_all(&len)
            .await
            .map_err(|e| InviteError::Connection(format!("send length: {e}")))?;
        send.write_all(&encrypted)
            .await
            .map_err(|e| InviteError::Connection(format!("send payload: {e}")))?;

        let _ = send.finish();

        // Remove the one-time invite
        self.pending.remove(&passphrase);
        self.cleanup_expired();

        log::info!("Invite accepted for project: {}", payload.project_name);
        Ok(())
    }
}

impl Default for InviteHandler {
    fn default() -> Self {
        Self::new()
    }
}

impl iroh::protocol::ProtocolHandler for InviteHandler {
    fn accept(
        &self,
        connection: Connection,
    ) -> impl std::future::Future<Output = Result<(), AcceptError>> + Send {
        let handler = InviteHandler {
            pending: Arc::clone(&self.pending),
        };

        async move {
            if let Err(e) = handler.handle_connection(connection).await {
                log::warn!("Invite handler error: {e}");
            }
            Ok(())
        }
    }
}

/// Errors in the invite flow.
#[derive(Debug, thiserror::Error)]
pub enum InviteError {
    #[error("Challenge-response verification failed — wrong passphrase")]
    VerificationFailed,

    #[error("Encryption failed")]
    CryptoError,

    #[error("Decryption failed — wrong key or tampered data")]
    DecryptionFailed,

    #[error("Invalid payload format")]
    InvalidPayload,

    #[error("Invite expired")]
    Expired,

    #[error("Too many handshake attempts")]
    Exhausted,

    #[error("Connection error: {0}")]
    Connection(String),

    #[error("Serialization error: {0}")]
    Serde(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_passphrase() {
        let phrase = generate_passphrase(6);
        let words: Vec<&str> = phrase.split('-').collect();
        assert_eq!(words.len(), 6);
        for word in &words {
            assert!(!word.is_empty());
        }
    }

    #[test]
    fn test_passphrase_uniqueness() {
        let p1 = generate_passphrase(6);
        let p2 = generate_passphrase(6);
        assert_ne!(p1, p2);
    }

    #[test]
    fn test_derive_key_deterministic() {
        let k1 = derive_key_from_passphrase("test-phrase");
        let k2 = derive_key_from_passphrase("test-phrase");
        assert_eq!(k1, k2);
    }

    #[test]
    fn test_derive_key_different_for_different_passphrases() {
        let k1 = derive_key_from_passphrase("phrase-a");
        let k2 = derive_key_from_passphrase("phrase-b");
        assert_ne!(k1, k2);
    }

    #[test]
    fn test_challenge_response_success() {
        let passphrase = "tiger-marble-ocean";
        let challenge = generate_challenge();
        let response = compute_challenge_response(passphrase, &challenge);
        assert!(verify_challenge_response(passphrase, &challenge, &response));
    }

    #[test]
    fn test_challenge_response_wrong_passphrase() {
        let challenge = generate_challenge();
        let response = compute_challenge_response("correct-phrase", &challenge);
        assert!(!verify_challenge_response(
            "wrong-phrase",
            &challenge,
            &response
        ));
    }

    #[test]
    fn test_challenge_response_different_challenges() {
        let passphrase = "test-phrase";
        let c1 = generate_challenge();
        let c2 = generate_challenge();
        let r1 = compute_challenge_response(passphrase, &c1);
        let r2 = compute_challenge_response(passphrase, &c2);
        // Different challenges produce different responses
        assert_ne!(r1, r2);
        // Can't use one response for a different challenge
        assert!(!verify_challenge_response(passphrase, &c2, &r1));
    }

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let key = derive_key_from_passphrase("test-encrypt");
        let plaintext = b"Hello, this is secret project data!";

        let encrypted = encrypt_payload(&key, plaintext).unwrap();
        assert_ne!(encrypted, plaintext); // Sanity check

        let decrypted = decrypt_payload(&key, &encrypted).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_decrypt_with_wrong_key_fails() {
        let key1 = derive_key_from_passphrase("phrase-a");
        let key2 = derive_key_from_passphrase("phrase-b");

        let plaintext = b"secret data";
        let encrypted = encrypt_payload(&key1, plaintext).unwrap();

        let result = decrypt_payload(&key2, &encrypted);
        assert!(matches!(result, Err(InviteError::DecryptionFailed)));
    }

    #[test]
    fn test_decrypt_truncated_data_fails() {
        let result = decrypt_payload(&[0u8; 32], &[0u8; 10]);
        assert!(matches!(result, Err(InviteError::InvalidPayload)));
    }

    #[test]
    fn test_invite_code_serde() {
        let code = InviteCode {
            passphrase: "tiger-marble-ocean-violet-canyon-frost".to_string(),
            peer_id: "abc123".to_string(),
            expires_at: chrono::Utc::now() + chrono::Duration::minutes(10),
        };

        let json = serde_json::to_string(&code).unwrap();
        let decoded: InviteCode = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.passphrase, code.passphrase);
        assert_eq!(decoded.peer_id, code.peer_id);
    }

    #[test]
    fn test_invite_payload_serde() {
        let payload = InvitePayload {
            project_id: "test-uuid".to_string(),
            project_name: "My Project".to_string(),
            role: "editor".to_string(),
            manifest_hex: "deadbeef".to_string(),
        };

        let json = serde_json::to_string(&payload).unwrap();
        let decoded: InvitePayload = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.project_name, "My Project");
    }

    fn test_pending_invite() -> PendingInvite {
        PendingInvite {
            code: InviteCode {
                passphrase: "test".to_string(),
                peer_id: "id".to_string(),
                expires_at: chrono::Utc::now(),
            },
            created_at: Instant::now(),
            attempts: 0,
            project_name: "test".to_string(),
            project_id: "test-id".to_string(),
            derived_key: [0u8; 32],
            manifest_data: vec![],
            invite_role: "editor".to_string(),
        }
    }

    #[test]
    fn test_pending_invite_expiry() {
        let mut invite = test_pending_invite();
        invite.created_at = Instant::now() - Duration::from_secs(700);
        assert!(invite.is_expired());
    }

    #[test]
    fn test_pending_invite_not_expired() {
        let invite = test_pending_invite();
        assert!(!invite.is_expired());
    }

    #[test]
    fn test_pending_invite_exhausted() {
        let mut invite = test_pending_invite();
        invite.attempts = 3;
        assert!(invite.is_exhausted());
    }
}
