pub mod blame;
pub mod doc_store;
pub mod error;
pub mod manifest;
pub mod persistence;
pub mod project;
pub mod search;
pub mod seen_state;
pub mod settings;
pub mod types;
pub mod validation;
pub mod version;
pub mod version_store;

pub use blame::get_document_blame;
pub use doc_store::DocStore;
pub use error::CoreError;
pub use manifest::ProjectManifest;
pub use project::ProjectManager;
pub use search::{SearchIndex, SearchResult};
pub use seen_state::{ProjectSeenState, SeenStateManager, UnseenDocInfo};
pub use settings::{AppSettings, DegradationLevel};
pub use types::*;
pub use validation::{validate_note_path, validate_project_name, validate_relative_path};
pub use version::{Version, VersionSignificance, VersionType};
pub use version_store::VersionStore;
